--Grupo:
--Gabriel Rodrigues da Silva - 121044858
--Giovanni Paes Leme da Gama Rodrigues - 117054744
--Gabriel Brígido Pinheiro da Silva - 120056519
--Nicolas Viana do Espírito Santo - 121042953

-- MySQL Script generated by MySQL Workbench
-- Sun Jun  1 22:18:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MarcaVeiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MarcaVeiculo` (
  `ID_MARCA_VEICULO` INT NOT NULL,
  `NOME_MARCA` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_MARCA_VEICULO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ModeloVeiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ModeloVeiculo` (
  `ID_MODELO_VEICULO` INT NOT NULL,
  `NOME_MODELO` VARCHAR(50) NOT NULL,
  `FK_ID_MARCA_VEICULO` INT NOT NULL,
  PRIMARY KEY (`ID_MODELO_VEICULO`),
  INDEX `fk_ModeloVeiculo_MarcaVeiculo1_idx` (`FK_ID_MARCA_VEICULO` ASC) VISIBLE,
  CONSTRAINT `fk_ModeloVeiculo_MarcaVeiculo1`
    FOREIGN KEY (`FK_ID_MARCA_VEICULO`)
    REFERENCES `mydb`.`MarcaVeiculo` (`ID_MARCA_VEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GrupoVeiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GrupoVeiculo` (
  `ID_GRUPO_VEICULO` INT NOT NULL,
  `NOME_GRUPO` VARCHAR(100) NOT NULL,
  `DESCRICAO_GRUPO` VARCHAR(255) NULL,
  `VALOR_DIARIA_BASE_GRUPO` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID_GRUPO_VEICULO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `ID_EMPRESA` INT NOT NULL,
  `NOME_EMPRESA` VARCHAR(100) NOT NULL,
  `CNPJ_EMPRESA` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`ID_EMPRESA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `SIGLA_ESTADO` VARCHAR(2) NOT NULL,
  `NOME_ESTADO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`SIGLA_ESTADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `ID_CIDADE` INT NOT NULL,
  `NOME_CIDADE` VARCHAR(100) NOT NULL,
  `FK_SIGLA_ESTADO` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`ID_CIDADE`),
  INDEX `fk_Cidade_Estado_idx` (`FK_SIGLA_ESTADO` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado`
    FOREIGN KEY (`FK_SIGLA_ESTADO`)
    REFERENCES `mydb`.`Estado` (`SIGLA_ESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `ID_BAIRRO` INT NOT NULL,
  `NOME_BAIRRO` VARCHAR(100) NOT NULL,
  `FK_ID_CIDADE` INT NOT NULL,
  PRIMARY KEY (`ID_BAIRRO`),
  INDEX `fk_Bairro_Cidade1_idx` (`FK_ID_CIDADE` ASC) VISIBLE,
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`FK_ID_CIDADE`)
    REFERENCES `mydb`.`Cidade` (`ID_CIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `ID_ENDERECO` INT NOT NULL,
  `LOGRADOURO` VARCHAR(200) NOT NULL,
  `NUMERO_LOGRADOURO` VARCHAR(20) NOT NULL,
  `COMPLEMENTO` VARCHAR(100) NULL,
  `CEP` VARCHAR(9) NOT NULL,
  `PONTO_REFERENCIA` VARCHAR(255) NULL,
  `FK_ID_BAIRRO` INT NOT NULL,
  PRIMARY KEY (`ID_ENDERECO`),
  INDEX `fk_Endereco_Bairro1_idx` (`FK_ID_BAIRRO` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Bairro1`
    FOREIGN KEY (`FK_ID_BAIRRO`)
    REFERENCES `mydb`.`Bairro` (`ID_BAIRRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patio` (
  `ID_PATIO` INT NOT NULL,
  `NOME_PATIO` VARCHAR(100) NOT NULL,
  `FK_ID_ENDERECO` INT NOT NULL,
  `FK_ID_EMPRESA` INT NOT NULL,
  PRIMARY KEY (`ID_PATIO`),
  INDEX `fk_Patio_Endereco1_idx` (`FK_ID_ENDERECO` ASC) VISIBLE,
  INDEX `fk_Patio_Empresa1_idx` (`FK_ID_EMPRESA` ASC) VISIBLE,
  CONSTRAINT `fk_Patio_Endereco1`
    FOREIGN KEY (`FK_ID_ENDERECO`)
    REFERENCES `mydb`.`Endereco` (`ID_ENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patio_Empresa1`
    FOREIGN KEY (`FK_ID_EMPRESA`)
    REFERENCES `mydb`.`Empresa` (`ID_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vaga` (
  `ID_VAGA` INT NOT NULL,
  `CODIGO_VAGA` VARCHAR(20) NOT NULL,
  `STATUS_VAGA` VARCHAR(20) NOT NULL,
  `FK_ID_PATIO` INT NOT NULL,
  PRIMARY KEY (`ID_VAGA`),
  INDEX `fk_Vaga_Patio1_idx` (`FK_ID_PATIO` ASC) VISIBLE,
  CONSTRAINT `fk_Vaga_Patio1`
    FOREIGN KEY (`FK_ID_PATIO`)
    REFERENCES `mydb`.`Patio` (`ID_PATIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `ID_VEICULO` INT NOT NULL,
  `PLACA` VARCHAR(7) NOT NULL,
  `CHASSI` VARCHAR(17) NOT NULL,
  `COR_VEICULO` VARCHAR(30) NOT NULL,
  `TIPO_MECANIZACAO` VARCHAR(20) NOT NULL,
  `POSSUI_AR_CONDICIONADO` TINYINT NOT NULL,
  `POSSUI_CADEIRINHA_CRIANCA` TINYINT NOT NULL,
  `POSSUI_BEBE_CONFORTO` TINYINT NOT NULL,
  `ACESSORIOS_TEXTO` VARCHAR(255) NULL,
  `FOTOS_URL_TEXTO` VARCHAR(255) NULL,
  `PRONTUARIO_TEXTO` VARCHAR(255) NULL,
  `STATUS_VEICULO` VARCHAR(20) NOT NULL,
  `FK_ID_MODELO_VEICULO` INT NOT NULL,
  `FK_ID_GRUPO_VEICULO` INT NOT NULL,
  `FK_ID_EMPRESA` INT NOT NULL,
  `FK_ID_PATIO` INT NULL,
  `FK_ID_VAGA` INT NULL,
  PRIMARY KEY (`ID_VEICULO`),
  INDEX `fk_Veiculo_ModeloVeiculo1_idx` (`FK_ID_MODELO_VEICULO` ASC) VISIBLE,
  INDEX `fk_Veiculo_GrupoVeiculo1_idx` (`FK_ID_GRUPO_VEICULO` ASC) VISIBLE,
  INDEX `fk_Veiculo_Empresa1_idx` (`FK_ID_EMPRESA` ASC) VISIBLE,
  INDEX `fk_Veiculo_Patio1_idx` (`FK_ID_PATIO` ASC) VISIBLE,
  INDEX `fk_Veiculo_Vaga1_idx` (`FK_ID_VAGA` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_ModeloVeiculo1`
    FOREIGN KEY (`FK_ID_MODELO_VEICULO`)
    REFERENCES `mydb`.`ModeloVeiculo` (`ID_MODELO_VEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_GrupoVeiculo1`
    FOREIGN KEY (`FK_ID_GRUPO_VEICULO`)
    REFERENCES `mydb`.`GrupoVeiculo` (`ID_GRUPO_VEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_Empresa1`
    FOREIGN KEY (`FK_ID_EMPRESA`)
    REFERENCES `mydb`.`Empresa` (`ID_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_Patio1`
    FOREIGN KEY (`FK_ID_PATIO`)
    REFERENCES `mydb`.`Patio` (`ID_PATIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_Vaga1`
    FOREIGN KEY (`FK_ID_VAGA`)
    REFERENCES `mydb`.`Vaga` (`ID_VAGA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `ID_CLIENTE` INT NOT NULL,
  `NOME_CLIENTE` VARCHAR(255) NOT NULL,
  `DOCUMENTO` VARCHAR(18) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `TELEFONE` VARCHAR(20) NOT NULL,
  `FK_ID_ENDERECO` INT NOT NULL,
  `TIPO_PESSOA` CHAR(1) NOT NULL,
  PRIMARY KEY (`ID_CLIENTE`),
  INDEX `fk_Cliente_Endereco1_idx` (`FK_ID_ENDERECO` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`FK_ID_ENDERECO`)
    REFERENCES `mydb`.`Endereco` (`ID_ENDERECO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Condutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Condutor` (
  `ID_CONDUTOR` INT NOT NULL,
  `NOME_CONDUTOR` VARCHAR(255) NOT NULL,
  `CPF_CONDUTOR` VARCHAR(14) NOT NULL,
  `NUMERO_CNH` VARCHAR(20) NOT NULL,
  `CATEGORIA_CNH` VARCHAR(5) NOT NULL,
  `DATA_VALIDADE_CNH` DATE NOT NULL,
  `FK_ID_CLIENTE` INT NULL,
  PRIMARY KEY (`ID_CONDUTOR`),
  INDEX `fk_Condutor_Cliente1_idx` (`FK_ID_CLIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_Condutor_Cliente1`
    FOREIGN KEY (`FK_ID_CLIENTE`)
    REFERENCES `mydb`.`Cliente` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Locacao` (
  `ID_LOCACAO` INT NOT NULL,
  `DATA_HORA_RETIRADA_PREVISTA` TIMESTAMP NOT NULL,
  `DATA_HORA_RETIRADA_REALIZADA` TIMESTAMP NOT NULL,
  `DATA_HORA_DEVOLUCAO_PREVISTA` TIMESTAMP NOT NULL,
  `DATA_HORA_DEVOLUCAO_REALIZADA` TIMESTAMP NULL,
  `VALOR_DIARIA_CONTRATADA` DECIMAL(10,2) NOT NULL,
  `STATUS_LOCACAO` VARCHAR(20) NOT NULL,
  `FK_ID_CLIENTE` INT NOT NULL,
  `FK_ID_CONDUTOR` INT NOT NULL,
  `FK_ID_VEICULO` INT NOT NULL,
  `FK_ID_PATIO_RETIRADA` INT NOT NULL,
  `FK_ID_PATIO_DEVOLUCAO` INT NULL,
  PRIMARY KEY (`ID_LOCACAO`),
  INDEX `fk_Locacao_Cliente1_idx` (`FK_ID_CLIENTE` ASC) VISIBLE,
  INDEX `fk_Locacao_Condutor1_idx` (`FK_ID_CONDUTOR` ASC) VISIBLE,
  INDEX `fk_Locacao_Veiculo1_idx` (`FK_ID_VEICULO` ASC) VISIBLE,
  INDEX `fk_Locacao_Patio1_idx` (`FK_ID_PATIO_DEVOLUCAO` ASC) VISIBLE,
  INDEX `fk_Locacao_Patio2_idx` (`FK_ID_PATIO_RETIRADA` ASC) VISIBLE,
  CONSTRAINT `fk_Locacao_Cliente1`
    FOREIGN KEY (`FK_ID_CLIENTE`)
    REFERENCES `mydb`.`Cliente` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Condutor1`
    FOREIGN KEY (`FK_ID_CONDUTOR`)
    REFERENCES `mydb`.`Condutor` (`ID_CONDUTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Veiculo1`
    FOREIGN KEY (`FK_ID_VEICULO`)
    REFERENCES `mydb`.`Veiculo` (`ID_VEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Patio1`
    FOREIGN KEY (`FK_ID_PATIO_DEVOLUCAO`)
    REFERENCES `mydb`.`Patio` (`ID_PATIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locacao_Patio2`
    FOREIGN KEY (`FK_ID_PATIO_RETIRADA`)
    REFERENCES `mydb`.`Patio` (`ID_PATIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cobranca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cobranca` (
  `ID_COBRANCA` INT NOT NULL,
  `DATA_HORA_EMISSAO` TIMESTAMP NOT NULL,
  `TIPO_COBRANCA` VARCHAR(30) NOT NULL,
  `VALOR_COBRANCA` DECIMAL(10,2) NOT NULL,
  `DATA_HORA_PAGAMENTO` TIMESTAMP NULL,
  `STATUS_COBRANCA` VARCHAR(20) NOT NULL,
  `FK_ID_LOCACAO` INT NOT NULL,
  PRIMARY KEY (`ID_COBRANCA`),
  INDEX `fk_Cobranca_Locacao1_idx` (`FK_ID_LOCACAO` ASC) VISIBLE,
  CONSTRAINT `fk_Cobranca_Locacao1`
    FOREIGN KEY (`FK_ID_LOCACAO`)
    REFERENCES `mydb`.`Locacao` (`ID_LOCACAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProtecaoAdicional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProtecaoAdicional` (
  `ID_PROTECAO_ADICIONAL` INT NOT NULL,
  `NOME_PROTECAO` VARCHAR(100) NOT NULL,
  `DESCRICAO_PROTECAO` VARCHAR(255) NULL,
  `VALOR_DIARIO_PROTECAO` DECIMAL(10,2) NOT NULL,
  `ATIVO_PROTECAO` TINYINT NOT NULL,
  PRIMARY KEY (`ID_PROTECAO_ADICIONAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `ID_RESERVA` INT NOT NULL,
  `DATA_HORA_SOLICITACAO_RESERVA` TIMESTAMP NOT NULL,
  `DATA_HORA_PREVISTA_RETIRADA` TIMESTAMP NOT NULL,
  `DATA_HORA_PREVISTA_DEVOLUCAO` TIMESTAMP NOT NULL,
  `STATUS_RESERVA` VARCHAR(20) NOT NULL,
  `FK_ID_CLIENTE` INT NOT NULL,
  `FK_ID_GRUPO_VEICULO` INT NOT NULL,
  `FK_ID_PATIO_RETIRADA` INT NOT NULL,
  `FK_ID_PATIO_DEVOLUCAO` INT NOT NULL,
  PRIMARY KEY (`ID_RESERVA`),
  INDEX `fk_Reserva_Cliente1_idx` (`FK_ID_CLIENTE` ASC) VISIBLE,
  INDEX `fk_Reserva_GrupoVeiculo1_idx` (`FK_ID_GRUPO_VEICULO` ASC) VISIBLE,
  INDEX `fk_Reserva_Patio1_idx` (`FK_ID_PATIO_RETIRADA` ASC) VISIBLE,
  INDEX `fk_Reserva_Patio2_idx` (`FK_ID_PATIO_DEVOLUCAO` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`FK_ID_CLIENTE`)
    REFERENCES `mydb`.`Cliente` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_GrupoVeiculo1`
    FOREIGN KEY (`FK_ID_GRUPO_VEICULO`)
    REFERENCES `mydb`.`GrupoVeiculo` (`ID_GRUPO_VEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Patio1`
    FOREIGN KEY (`FK_ID_PATIO_RETIRADA`)
    REFERENCES `mydb`.`Patio` (`ID_PATIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Patio2`
    FOREIGN KEY (`FK_ID_PATIO_DEVOLUCAO`)
    REFERENCES `mydb`.`Patio` (`ID_PATIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LocacaoProtecao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LocacaoProtecao` (
  `FK_ID_LOCACAO` INT NOT NULL,
  `FK_ID_PROTECAO_ADICIONAL` INT NOT NULL,
  `VALOR_PROTECAO_APLICADO` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`FK_ID_LOCACAO`, `FK_ID_PROTECAO_ADICIONAL`),
  INDEX `fk_LocacaoProtecao_ProtecaoAdicional1_idx` (`FK_ID_PROTECAO_ADICIONAL` ASC) VISIBLE,
  CONSTRAINT `fk_LocacaoProtecao_Locacao1`
    FOREIGN KEY (`FK_ID_LOCACAO`)
    REFERENCES `mydb`.`Locacao` (`ID_LOCACAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LocacaoProtecao_ProtecaoAdicional1`
    FOREIGN KEY (`FK_ID_PROTECAO_ADICIONAL`)
    REFERENCES `mydb`.`ProtecaoAdicional` (`ID_PROTECAO_ADICIONAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
